/**
 * Type-only view of the contract surface. The schemas themselves live in @/schemas
 * (generated from pipeline/schemas/ — see src/schemas/index.ts); this module exists so
 * components can import plain types without pulling Zod into their import graph.
 */
export type {
  AnalysisDataset,
  CalendarDataset,
  CalendarEvent,
  CaseStatement,
  CryptoAsset,
  CryptoDataset,
  CryptoSentiment,
  DriverContribution,
  EquitiesDataset,
  EquityAsset,
  EventImportance,
  EventType,
  FactLayer,
  FedWatchRateProb,
  FedWatchSnapshot,
  MacroDataset,
  MacroIndicator,
  MacroUnit,
  Market,
  MarketRegime,
  MemoryProxy,
  NewsDataset,
  NewsItem,
  NewsSentiment,
  NewsTranslation,
  NewsTranslationsDataset,
  RiskDimension,
  RiskDimensionKey,
  RiskDirection,
  RiskIndicator,
  RiskLevel,
  RiskModelResult,
  RiskTrend,
  SectorItem,
  SectorsDataset,
  SignalClaim,
} from "@/schemas";
