"""Pydantic contract tests (T02 acceptance: the same fixture passes Pydantic validation + hard constraints).

Covers:
- All core dataset documents (factory-generated since #73) pass the corresponding envelope /
  self-describing model validation
- The three hand-written golden documents (tests/fixtures/{risk,analysis.zh-CN,facts}.json) pass
  their models — they are the cross-language hinge tests/frontend/schemas.test.ts reads
- No implicit fields (extra="forbid")
- Rejects NaN/Infinity
- Strict enum/time validation, numeric range validation
- The factory's output is at least as representative as each golden (structure conformance)
- schema_version support and backward-compatibility check
"""

from __future__ import annotations

import json
from collections.abc import Callable
from pathlib import Path
from typing import Any

import pytest
from pydantic import ValidationError

from pipeline.schemas import (
    AnalysisDataset,
    BaseEnvelope,
    CalendarEnvelope,
    CryptoEnvelope,
    DashboardEnvelope,
    EquitiesEnvelope,
    FactLayer,
    MacroEnvelope,
    NewsEnvelope,
    RiskEnvelope,
    SectorsEnvelope,
)
from pipeline.schemas.envelope import SCHEMA_VERSION, is_schema_compatible
from tests.pipeline.factories import make_analysis, make_envelope, make_facts

FIXTURES = Path(__file__).resolve().parent.parent / "fixtures"

# Dataset keys aligned with Python (architecture §8.1). Documents are generated by the
# factory (#73): the static fixture bundle is gone.
ENVELOPE_FIXTURES: dict[str, type[BaseEnvelope]] = {
    "macro.json": MacroEnvelope,
    "equities.json": EquitiesEnvelope,
    "sectors.json": SectorsEnvelope,
    "crypto.json": CryptoEnvelope,
    "news.json": NewsEnvelope,
    "calendar.json": CalendarEnvelope,
    "risk.json": RiskEnvelope,
    "dashboard.json": DashboardEnvelope,
}

# Self-describing contract files (facts / analysis are not wrapped in BaseEnvelope; see contract.py)
STANDALONE_FIXTURES: dict[str, type] = {
    "facts.json": FactLayer,
    "analysis.zh-CN.json": AnalysisDataset,
    "analysis.en.json": AnalysisDataset,
}

#: The three hand-written golden documents that survived #73. They are independent of the
#: factory by construction, and they are the files tests/frontend/schemas.test.ts reads — the
#: cross-language backstop that keeps the Zod mirror following Pydantic.
GOLDEN_MODELS: dict[str, type] = {
    "risk.json": RiskEnvelope,
    "facts.json": FactLayer,
    "analysis.zh-CN.json": AnalysisDataset,
}


def load_fixture(name: str) -> dict:
    return json.loads((FIXTURES / name).read_text(encoding="utf-8"))


def generated_document(name: str) -> dict:
    """The factory's document for `name`, replacing the deleted static fixtures."""
    if name == "facts.json":
        return make_facts()
    if name in ("analysis.zh-CN.json", "analysis.en.json"):
        return make_analysis(language=name.removesuffix(".json").removeprefix("analysis."))
    return make_envelope(name.removesuffix(".json"))


def _structure_key_paths(doc: Any, prefix: str = "") -> set[str]:
    """Every key path in `doc`; a list contributes the first element's paths under `[]`."""
    paths: set[str] = set()
    if isinstance(doc, dict):
        for key, value in doc.items():
            path = f"{prefix}.{key}" if prefix else key
            paths.add(path)
            paths |= _structure_key_paths(value, path)
    elif isinstance(doc, list) and doc:
        paths |= _structure_key_paths(doc[0], f"{prefix}[]")
    return paths


# ---------- Positive: all documents valid ----------

@pytest.mark.parametrize("name,model", ENVELOPE_FIXTURES.items())
def test_envelope_fixtures_valid(name: str, model: type[BaseEnvelope]) -> None:
    parsed = model.model_validate(generated_document(name))
    assert parsed.freshness_status in ("fresh", "delayed", "stale", "missing", "degraded")
    assert 0.0 <= parsed.data_quality <= 1.0


@pytest.mark.parametrize("name,model", STANDALONE_FIXTURES.items())
def test_standalone_fixtures_valid(name: str, model: type) -> None:
    model.model_validate(generated_document(name))


@pytest.mark.parametrize("name,model", GOLDEN_MODELS.items())
def test_golden_documents_valid(name: str, model: type) -> None:
    """The goldens themselves stay valid — they are the anchor both languages read."""
    model.model_validate(load_fixture(name))


# ---------- Negative: hard constraints ----------

def _valid_macro() -> dict:
    return generated_document("macro.json")


def test_rejects_nan() -> None:
    data = _valid_macro()
    data["payload"]["rates"][0]["value"] = float("nan")
    with pytest.raises(ValidationError):
        MacroEnvelope.model_validate(data)


def test_rejects_infinity() -> None:
    data = _valid_macro()
    data["payload"]["rates"][0]["value"] = float("inf")
    with pytest.raises(ValidationError):
        MacroEnvelope.model_validate(data)


def test_rejects_extra_fields() -> None:
    data = _valid_macro()
    data["extra_key"] = "should_fail"
    with pytest.raises(ValidationError):
        MacroEnvelope.model_validate(data)
    data2 = _valid_macro()
    data2["payload"]["rates"][0]["sneaky"] = 1
    with pytest.raises(ValidationError):
        MacroEnvelope.model_validate(data2)


def test_rejects_bad_enum() -> None:
    data = _valid_macro()
    data["freshness_status"] = "not_a_status"
    with pytest.raises(ValidationError):
        MacroEnvelope.model_validate(data)


def test_rejects_bad_datetime() -> None:
    data = _valid_macro()
    data["generated_at"] = "2026-08-03 10:00:00"
    with pytest.raises(ValidationError):
        MacroEnvelope.model_validate(data)
    data2 = _valid_macro()
    data2["generated_at"] = "2026-08-03T10:00:00+08:00"  # non-Z suffix
    with pytest.raises(ValidationError):
        MacroEnvelope.model_validate(data2)


def test_rejects_out_of_range() -> None:
    data = _valid_macro()
    data["data_quality"] = 1.5
    with pytest.raises(ValidationError):
        MacroEnvelope.model_validate(data)
    risk = load_fixture("risk.json")
    risk["payload"]["total_score"] = 120.0
    with pytest.raises(ValidationError):
        RiskEnvelope.model_validate(risk)


def test_rejects_missing_required() -> None:
    data = _valid_macro()
    del data["generated_at"]
    with pytest.raises(ValidationError):
        MacroEnvelope.model_validate(data)


# ---------- #73 board-ruled AC: a golden that lies fails both languages ----------

@pytest.mark.parametrize("name,model", GOLDEN_MODELS.items())
def test_golden_rejects_unknown_keys(name: str, model: type) -> None:
    """Injecting an unknown key into a golden must fail Pydantic (extra="forbid").

    The same probe on the frontend side (tests/frontend/schemas.test.ts) must fail the Zod
    `.strict()` mirror — that is the cross-language backstop #73 exists to preserve.
    """
    doc = load_fixture(name)
    doc["sneaky_extra"] = 1
    with pytest.raises(ValidationError):
        model.model_validate(doc)


# ---------- #73: the factory must be at least as representative as the goldens ----------

_GOLDEN_FACTORY: dict[str, Callable[[], dict[str, Any]]] = {
    "risk.json": lambda: make_envelope("risk"),
    "facts.json": make_facts,
    "analysis.zh-CN.json": lambda: make_analysis(language="zh-CN"),
}


@pytest.mark.parametrize("name", sorted(_GOLDEN_FACTORY))
def test_factory_output_matches_golden_structure(name: str) -> None:
    """The factory's output has every key path the hand-written golden has.

    #73: the goldens are the independent documents the suite is anchored to. If the factory
    drifts — emits a valid but *unrepresentative* document (a proxy never set, a nesting level
    no real run produces) — a golden key path it no longer produces shows up here as missing.
    Values are free to differ; structure is not. The mutation probe (delete a field from a
    factory default) must make this test red.
    """
    golden = load_fixture(name)
    factory_doc = _GOLDEN_FACTORY[name]()
    missing = _structure_key_paths(golden) - _structure_key_paths(factory_doc)
    assert not missing, (
        f"factory output for {name} is missing golden key paths: {sorted(missing)}"
    )


# ---------- schema_version support and backward compatibility ----------

def test_schema_version_supported() -> None:
    for name, model in ENVELOPE_FIXTURES.items():
        data = generated_document(name)
        assert data["schema_version"] == SCHEMA_VERSION
        model.model_validate(data)


@pytest.mark.parametrize(
    "file_version,expected",
    [
        ("1.0.0", True),   # current version
        ("1.0.1", True),   # same major, patch ignored
        ("1.1.0", False),  # future minor: new fields may be incompatible (extra=forbid)
        ("2.0.0", False),  # different major: structure incompatible
        ("0.9.0", False),  # earlier major
        ("not-a-version", False),
    ],
)
def test_is_schema_compatible(file_version: str, expected: bool) -> None:
    assert is_schema_compatible(file_version, SCHEMA_VERSION) is expected


# ---------- Copy isolation: negative cases do not pollute shared documents ----------

def test_generated_documents_remain_valid_after_negative_tests() -> None:
    """Negative cases deep-copy via fresh factory calls; regeneration must stay valid."""
    for name, model in ENVELOPE_FIXTURES.items():
        model.model_validate(generated_document(name))
    for name, model in GOLDEN_MODELS.items():
        model.model_validate(load_fixture(name))
